# Generated by Django 3.1.4 on 2020-12-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'actor',
                'verbose_name_plural': 'actors',
                'db_table': 'actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'director',
                'verbose_name_plural': 'directors',
                'db_table': 'directors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('kinopoisk_id', models.CharField(blank=True, max_length=30, null=True)),
                ('kinopoisk', models.FloatField(blank=True, null=True)),
                ('imdb', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('season', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'db_table': 'types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Years',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'year',
                'verbose_name_plural': 'years',
                'db_table': 'years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmsActors',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.films')),
            ],
            options={
                'verbose_name': 'films_actors',
                'verbose_name_plural': 'films_actors',
                'db_table': 'films_actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmsCountries',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.films')),
            ],
            options={
                'verbose_name': 'films_countries',
                'verbose_name_plural': 'films_countries',
                'db_table': 'films_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmsDirectors',
            fields=[
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.films')),
            ],
            options={
                'verbose_name': 'films_directors',
                'verbose_name_plural': 'films_directors',
                'db_table': 'films_directors',
                'managed': False,
            },
        ),
    ]
