# Generated by Django 3.1.4 on 2021-01-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='films',
            options={'managed': True, 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
    ]
