# Generated by Django 3.1.4 on 2021-01-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210118_1532'),
    ]

    operations = [

        migrations.AddField(
            model_name='films',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='films',
            name='id_genres',
            field=models.ForeignKey(blank=True, db_column='id_genres', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.genres', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='films',
            name='id_types',
            field=models.ForeignKey(blank=True, db_column='id_types', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.types', verbose_name='Тип (сезон)'),
        ),
        migrations.AddField(
            model_name='films',
            name='id_years',
            field=models.ForeignKey(blank=True, db_column='id_years', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.years', verbose_name='Год выхода'),
        ),
        migrations.AlterField(
            model_name='films',
            name='imdb',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг IMDB'),
        ),
        migrations.AlterField(
            model_name='films',
            name='kinopoisk',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Кинопоиск'),
        ),
        migrations.AlterField(
            model_name='films',
            name='kinopoisk_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Кинопоиск ID'),
        ),
        migrations.AlterField(
            model_name='films',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='films',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Длительность'),
        ),
    ]
