# Generated by Django 3.1.4 on 2021-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='films',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons', verbose_name='Иконка'),
        ),
    ]
