# Generated by Django 3.1.4 on 2021-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210118_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='icon',
            field=models.ImageField(blank=True, default='main/icons/none_icon.jpg', null=True, upload_to='main/icons/', verbose_name='Иконка'),
        ),
    ]
